//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGuard.ConfigValidation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGuard.ConfigValidation.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings loading failed: File path cannot be null or empty. Please provide a valid path to the app settings file (e.g., &apos;appsettings.json&apos; or &apos;appsettings.yaml&apos;)..
        /// </summary>
        public static string ArgumentException_AppSettingsPathNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentException_AppSettingsPathNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base path cannot be null or empty..
        /// </summary>
        public static string ArgumentException_BasePathNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentException_BasePathNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration loading failed: File path cannot be null or empty. Please provide a valid path to the configuration file (e.g., &apos;sguard.json&apos; or &apos;sguard.yaml&apos;)..
        /// </summary>
        public static string ArgumentException_ConfigPathNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentException_ConfigPathNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration JSON cannot be null or empty..
        /// </summary>
        public static string ArgumentException_ConfigJsonNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentException_ConfigJsonNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition value cannot be null for comparison.
        /// </summary>
        public static string ArgumentException_ConditionValueNull {
            get {
                return ResourceManager.GetString("ArgumentException_ConditionValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File operation failed: File path is required but was null or empty. Please provide a valid file path for the write operation..
        /// </summary>
        public static string ArgumentException_FilePathNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentException_FilePathNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File validation failed: File path is required but was null or empty. Please provide a valid path to the configuration file to validate..
        /// </summary>
        public static string ArgumentException_FilePathRequired {
            get {
                return ResourceManager.GetString("ArgumentException_FilePathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown output format: &apos;{0}&apos;. Supported formats: json, text, console.
        /// </summary>
        public static string ArgumentException_UnknownOutputFormat {
            get {
                return ResourceManager.GetString("ArgumentException_UnknownOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values are not comparable.
        /// </summary>
        public static string ArgumentException_ValuesNotComparable {
            get {
                return ResourceManager.GetString("ArgumentException_ValuesNotComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File validation failed: AppSettings cannot be null. File path: &apos;{0}&apos;. Please provide a non-null dictionary of app settings to validate against..
        /// </summary>
        public static string ArgumentNullException_AppSettings {
            get {
                return ResourceManager.GetString("ArgumentNullException_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File validation failed: Applicable rules cannot be null. File path: &apos;{0}&apos;. Please provide a non-null list of rules to apply during validation..
        /// </summary>
        public static string ArgumentNullException_ApplicableRules {
            get {
                return ResourceManager.GetString("ArgumentNullException_ApplicableRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings loading failed: File not found at path &apos;{0}&apos;. Resolved absolute path: &apos;{1}&apos;. Please ensure the file exists and the path is correct. Check for typos, verify the file location, and ensure you have read permissions..
        /// </summary>
        public static string ConfigurationException_AppSettingsFileNotFound {
            get {
                return ResourceManager.GetString("ConfigurationException_AppSettingsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings loading failed: File size exceeds security limit. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Actual size: {2:F2} MB ({3:N0} bytes). Maximum allowed: {4:F2} MB ({5:N0} bytes). Exceeded by: {6:F2} MB. This may indicate a DoS attack attempt or corrupted file. Please verify the file integrity and reduce its size if legitimate..
        /// </summary>
        public static string ConfigurationException_AppSettingsFileSizeExceedsLimit {
            get {
                return ResourceManager.GetString("ConfigurationException_AppSettingsFileSizeExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings loading failed: I/O error occurred while reading the file. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Error: {2}. Possible causes: file is locked by another process, disk is full, network path is unavailable, or insufficient permissions. Please check file access permissions and ensure the file is not in use by another application..
        /// </summary>
        public static string ConfigurationException_AppSettingsIOException {
            get {
                return ResourceManager.GetString("ConfigurationException_AppSettingsIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings loading failed: Invalid JSON format detected. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). JSON parsing error: {2}. Error location: {3}. Please verify the JSON syntax is valid (check for missing commas, brackets, quotes, etc.) and try again..
        /// </summary>
        public static string ConfigurationException_AppSettingsInvalidJsonFormat {
            get {
                return ResourceManager.GetString("ConfigurationException_AppSettingsInvalidJsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings loading failed: Unexpected error occurred. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Exception type: {2}. Error message: {3}. This is an unexpected error. Please check the logs for more details and contact support if the issue persists..
        /// </summary>
        public static string ConfigurationException_AppSettingsUnexpectedError {
            get {
                return ResourceManager.GetString("ConfigurationException_AppSettingsUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration loading failed: Deserialization returned null. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). File size: {2:N0} bytes. The file may be malformed, contain invalid JSON structure, or be empty after whitespace removal. Please verify the JSON syntax is valid and matches the expected SGuard configuration format..
        /// </summary>
        public static string ConfigurationException_DeserializationReturnedNull {
            get {
                return ResourceManager.GetString("ConfigurationException_DeserializationReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration loading failed: File is empty. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). The file exists but contains no content. Please ensure the file contains valid JSON or YAML configuration data..
        /// </summary>
        public static string ConfigurationException_FileEmpty {
            get {
                return ResourceManager.GetString("ConfigurationException_FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration loading failed: File not found at path &apos;{0}&apos;. Resolved absolute path: &apos;{1}&apos;. Please ensure the file exists and the path is correct. Check for typos, verify the file location, and ensure you have read permissions..
        /// </summary>
        public static string ConfigurationException_FileNotFound {
            get {
                return ResourceManager.GetString("ConfigurationException_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration loading failed: File size exceeds security limit. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Actual size: {2:F2} MB ({3:N0} bytes). Maximum allowed: {4:F2} MB ({5:N0} bytes). Exceeded by: {6:F2} MB. This may indicate a DoS attack attempt or corrupted file. Please verify the file integrity and reduce its size if legitimate..
        /// </summary>
        public static string ConfigurationException_FileSizeExceedsLimit {
            get {
                return ResourceManager.GetString("ConfigurationException_FileSizeExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration validation failed: Environment count exceeds security limit. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Actual count: {2} environments. Maximum allowed: {3} environments. Exceeded by: {4} environments. This may indicate a DoS attack attempt. Please reduce the number of environments or contact your administrator to adjust the security limits..
        /// </summary>
        public static string ConfigurationException_EnvironmentCountExceedsLimit {
            get {
                return ResourceManager.GetString("ConfigurationException_EnvironmentCountExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration loading failed: I/O error occurred while reading the file. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Error: {2}. Possible causes: file is locked by another process, disk is full, network path is unavailable, or insufficient permissions. Please check file access permissions and ensure the file is not in use by another application..
        /// </summary>
        public static string ConfigurationException_IOException {
            get {
                return ResourceManager.GetString("ConfigurationException_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration loading failed: Invalid JSON format detected. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). JSON parsing error: {2}. Error location: {3}. Please verify the JSON syntax is valid (check for missing commas, brackets, quotes, etc.) and try again..
        /// </summary>
        public static string ConfigurationException_InvalidJsonFormat {
            get {
                return ResourceManager.GetString("ConfigurationException_InvalidJsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON format in configuration: {0}.
        /// </summary>
        public static string ConfigurationException_InvalidJsonFormatSimple {
            get {
                return ResourceManager.GetString("ConfigurationException_InvalidJsonFormatSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize configuration JSON. The JSON may be malformed or empty..
        /// </summary>
        public static string ConfigurationException_JsonDeserializationFailed {
            get {
                return ResourceManager.GetString("ConfigurationException_JsonDeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration JSON must contain at least one environment definition..
        /// </summary>
        public static string ConfigurationException_JsonNoEnvironments {
            get {
                return ResourceManager.GetString("ConfigurationException_JsonNoEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration JSON validation failed:{0}{1}.
        /// </summary>
        public static string ConfigurationException_JsonValidationFailed {
            get {
                return ResourceManager.GetString("ConfigurationException_JsonValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration validation failed: No environments defined. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Found {2} rule(s) but 0 environments. At least one environment definition is required. Please add an &apos;environments&apos; array with at least one environment object containing &apos;id&apos;, &apos;name&apos;, and &apos;path&apos; properties..
        /// </summary>
        public static string ConfigurationException_NoEnvironments {
            get {
                return ResourceManager.GetString("ConfigurationException_NoEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration validation failed: No rules defined. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Found {2} environment(s) but 0 rules. At least one rule definition is required. Please add a &apos;rules&apos; array with at least one rule object..
        /// </summary>
        public static string ConfigurationException_NoRules {
            get {
                return ResourceManager.GetString("ConfigurationException_NoRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration validation failed: Rule count exceeds security limit. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Actual count: {2} rules. Maximum allowed: {3} rules. Exceeded by: {4} rules. This may indicate a DoS attack attempt. Please reduce the number of rules or contact your administrator to adjust the security limits..
        /// </summary>
        public static string ConfigurationException_RuleCountExceedsLimit {
            get {
                return ResourceManager.GetString("ConfigurationException_RuleCountExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration validation failed: File does not match the expected schema. Configuration file: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Schema file: &apos;{2}&apos; (absolute path: &apos;{3}&apos;). Validation errors:{4}{5} Please review the schema requirements and fix the configuration file accordingly..
        /// </summary>
        public static string ConfigurationException_SchemaValidationFailed {
            get {
                return ResourceManager.GetString("ConfigurationException_SchemaValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration validation failed: Structure validation found {0} error(s). File: &apos;{1}&apos; (absolute path: &apos;{2}&apos;). Validation errors:{3}{4} Please review each error above and fix the configuration file accordingly..
        /// </summary>
        public static string ConfigurationException_StructureValidationFailed {
            get {
                return ResourceManager.GetString("ConfigurationException_StructureValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration loading failed: Unexpected error occurred. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Exception type: {2}. Error message: {3}. This is an unexpected error. Please check the logs for more details and contact support if the issue persists..
        /// </summary>
        public static string ConfigurationException_UnexpectedError {
            get {
                return ResourceManager.GetString("ConfigurationException_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration loading failed: Access denied. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Error: {2}. The current user does not have read permissions for this file. Please check file permissions and ensure the file is readable by the current user or process..
        /// </summary>
        public static string ConfigurationException_YamlAccessDenied {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert YAML to JSON: {0}.
        /// </summary>
        public static string ConfigurationException_YamlConvertFailed {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlConvertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration loading failed: Deserialization returned null. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). YAML content size: {2:N0} characters. The file may be malformed, contain invalid YAML structure, or be empty after whitespace removal. Please verify the YAML syntax is valid and matches the expected SGuard configuration format..
        /// </summary>
        public static string ConfigurationException_YamlDeserializationReturnedNull {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlDeserializationReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML deserialization returned null.
        /// </summary>
        public static string ConfigurationException_YamlDeserializationNull {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlDeserializationNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration validation failed: Environment count exceeds security limit. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Actual count: {2} environments. Maximum allowed: {3} environments. Exceeded by: {4} environments. This may indicate a DoS attack attempt. Please reduce the number of environments or contact your administrator to adjust the security limits..
        /// </summary>
        public static string ConfigurationException_YamlEnvironmentCountExceedsLimit {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlEnvironmentCountExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration loading failed: File is empty. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). The file exists but contains no content. Please ensure the file contains valid YAML configuration data..
        /// </summary>
        public static string ConfigurationException_YamlFileEmpty {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration loading failed: File not found at path &apos;{0}&apos;. Resolved absolute path: &apos;{1}&apos;. Please ensure the file exists and the path is correct. Check for typos, verify the file location, and ensure you have read permissions..
        /// </summary>
        public static string ConfigurationException_YamlFileNotFound {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration loading failed: File size exceeds security limit. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Actual size: {2:F2} MB ({3:N0} bytes). Maximum allowed: {4:F2} MB ({5:N0} bytes). Exceeded by: {6:F2} MB. This may indicate a DoS attack attempt or corrupted file. Please verify the file integrity and reduce its size if legitimate..
        /// </summary>
        public static string ConfigurationException_YamlFileSizeExceedsLimit {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlFileSizeExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration loading failed: I/O error occurred while reading the file. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Error: {2}. Possible causes: file is locked by another process, disk is full, network path is unavailable, or insufficient permissions. Please check file access permissions and ensure the file is not in use by another application..
        /// </summary>
        public static string ConfigurationException_YamlIOException {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration loading failed: Error converting YAML to JSON. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). JSON conversion error: {2}. Error location: {3}. The YAML was parsed successfully but failed during JSON conversion. This may indicate unsupported YAML features or data type conversion issues. Please review the YAML structure and ensure compatibility with JSON conversion..
        /// </summary>
        public static string ConfigurationException_YamlJsonConversionError {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlJsonConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration validation failed: No environments defined. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Found {2} rule(s) but 0 environments. At least one environment definition is required. Please add an &apos;environments&apos; array with at least one environment object containing &apos;id&apos;, &apos;name&apos;, and &apos;path&apos; properties..
        /// </summary>
        public static string ConfigurationException_YamlNoEnvironments {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlNoEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse YAML: {0}.
        /// </summary>
        public static string ConfigurationException_YamlParseFailed {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration loading failed: YAML parsing error detected. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). YAML parsing error: {2}. Error location: {3}. Please verify the YAML syntax is valid (check indentation, colons, dashes, quotes, etc.) and try again..
        /// </summary>
        public static string ConfigurationException_YamlParsingError {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration validation failed: Rule count exceeds security limit. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Actual count: {2} rules. Maximum allowed: {3} rules. Exceeded by: {4} rules. This may indicate a DoS attack attempt. Please reduce the number of rules or contact your administrator to adjust the security limits..
        /// </summary>
        public static string ConfigurationException_YamlRuleCountExceedsLimit {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlRuleCountExceedsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to serialize YAML to JSON: {0}.
        /// </summary>
        public static string ConfigurationException_YamlSerializeFailed {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlSerializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML configuration loading failed: Unexpected error occurred. File: &apos;{0}&apos; (absolute path: &apos;{1}&apos;). Exception type: {2}. Error message: {3}. This is an unexpected error. Please check the logs for more details and contact support if the issue persists..
        /// </summary>
        public static string ConfigurationException_YamlUnexpectedError {
            get {
                return ResourceManager.GetString("ConfigurationException_YamlUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File operation failed: Directory not found. File path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). Error: {2}. The directory containing the file does not exist. Please ensure the directory path is valid..
        /// </summary>
        public static string FileNotFoundException_DirectoryNotFound {
            get {
                return ResourceManager.GetString("FileNotFoundException_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File operation failed: File not found. File path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). Please ensure the file exists and the path is correct. Check for typos, verify the file location, and ensure you have read permissions..
        /// </summary>
        public static string FileNotFoundException_FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFoundException_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSettings loading failed: File not found at path &apos;{0}&apos;. Resolved absolute path: &apos;{1}&apos;. Please ensure the file exists and the path is correct. Check for typos, verify the file location, and ensure you have read permissions..
        /// </summary>
        public static string FileNotFoundException_AppSettings {
            get {
                return ResourceManager.GetString("FileNotFoundException_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert value &apos;{0}&apos; to int for {1} validator.
        /// </summary>
        public static string InvalidOperationException_CannotConvertToInt {
            get {
                return ResourceManager.GetString("InvalidOperationException_CannotConvertToInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File operation failed: Unexpected error occurred while writing file. File path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). Exception type: {2}. Error: {3}. This is an unexpected error. Please check the logs for more details..
        /// </summary>
        public static string InvalidOperationException_FileWriteUnexpectedError {
            get {
                return ResourceManager.GetString("InvalidOperationException_FileWriteUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator type &apos;{0}&apos; is not supported. Supported validators: {1}.
        /// </summary>
        public static string NotSupportedException_ValidatorTypeNotSupported {
            get {
                return ResourceManager.GetString("NotSupportedException_ValidatorTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File operation failed: Cannot create directory. Directory path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). Exception type: {2}. Error: {3}. Please ensure you have write permissions for the parent directory and that the path is valid..
        /// </summary>
        public static string UnauthorizedAccessException_CannotCreateDirectory {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_CannotCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to directory: {0}.
        /// </summary>
        public static string UnauthorizedAccessException_CannotWriteDirectory {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_CannotWriteDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File operation failed: Directory not found. File path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). Error: {2}. The directory containing the file does not exist and could not be created. Please ensure the directory path is valid and you have permissions to create directories..
        /// </summary>
        public static string UnauthorizedAccessException_DirectoryNotFound {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File operation failed: Insufficient read permissions. File path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). The current user does not have read permissions for this file. Please check file permissions and ensure the file is readable by the current user or process..
        /// </summary>
        public static string UnauthorizedAccessException_InsufficientReadPermissions {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_InsufficientReadPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File operation failed: Insufficient write permissions. File path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). The current user does not have write permissions for this file. Please check file permissions and ensure the file is writable by the current user or process..
        /// </summary>
        public static string UnauthorizedAccessException_InsufficientWritePermissions {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_InsufficientWritePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path security validation failed: Path traversal attack detected. Resolved path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). Base directory: &apos;{2}&apos; (absolute: &apos;{3}&apos;). The resolved path is outside the allowed base directory. This is a security violation and the operation has been blocked. Please ensure all file paths are relative to the base directory and do not contain path traversal sequences (..)..
        /// </summary>
        public static string UnauthorizedAccessException_PathTraversalDetected {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_PathTraversalDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path security validation failed: Resolved path or base path is null or empty. Resolved path: {0}. Base path: {1}. Both paths must be non-null and non-empty for security validation..
        /// </summary>
        public static string UnauthorizedAccessException_PathSecurityNullEmpty {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_PathSecurityNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path security validation failed: Unexpected error occurred during path validation. Resolved path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). Base path: &apos;{2}&apos; (absolute: &apos;{3}&apos;). Exception type: {4}. Error: {5}. This is an unexpected error. Please check the logs for more details..
        /// </summary>
        public static string UnauthorizedAccessException_PathValidationUnexpectedError {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_PathValidationUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path security validation failed: Symlink attack detected. Symlink path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). Symlink target: &apos;{2}&apos; (absolute: &apos;{3}&apos;). Base directory: &apos;{4}&apos; (absolute: &apos;{5}&apos;). The symlink target is outside the allowed base directory. This is a security violation and the operation has been blocked. Please ensure all symlinks point to files within the base directory..
        /// </summary>
        public static string UnauthorizedAccessException_SymlinkAttackDetected {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_SymlinkAttackDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path security validation failed: Symlink detected but unable to resolve target. Symlink path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). Base path: &apos;{2}&apos; (absolute: &apos;{3}&apos;). Unable to determine the symlink target, which is required for security validation. Symlinks pointing to unresolvable targets are not allowed for security reasons..
        /// </summary>
        public static string UnauthorizedAccessException_SymlinkUnresolvable {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_SymlinkUnresolvable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path security validation failed: Unexpected error occurred during symlink validation. Symlink path: &apos;{0}&apos; (absolute: &apos;{1}&apos;). Base path: &apos;{2}&apos; (absolute: &apos;{3}&apos;). Exception type: {4}. Error: {5}. Unable to verify symlink target is safe. This is an unexpected error. Please check the logs for more details..
        /// </summary>
        public static string UnauthorizedAccessException_SymlinkValidationUnexpectedError {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_SymlinkValidationUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create temporary directory. Original error: {0}.
        /// </summary>
        public static string UnauthorizedAccessException_UnableCreateTempDirectory {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException_UnableCreateTempDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string ConsoleOutput_Error {
            get {
                return ResourceManager.GetString("ConsoleOutput_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Details: {0}.
        /// </summary>
        public static string ConsoleOutput_ErrorDetails {
            get {
                return ResourceManager.GetString("ConsoleOutput_ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Environments:.
        /// </summary>
        public static string ConsoleOutput_ValidatingEnvironments {
            get {
                return ResourceManager.GetString("ConsoleOutput_ValidatingEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All validations passed successfully!.
        /// </summary>
        public static string ConsoleOutput_AllValidationsPassed {
            get {
                return ResourceManager.GetString("ConsoleOutput_AllValidationsPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} validation error(s) found..
        /// </summary>
        public static string ConsoleOutput_ValidationErrorsFound {
            get {
                return ResourceManager.GetString("ConsoleOutput_ValidationErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment: {0}.
        /// </summary>
        public static string ConsoleOutput_Environment {
            get {
                return ResourceManager.GetString("ConsoleOutput_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    File: {0}.
        /// </summary>
        public static string ConsoleOutput_File {
            get {
                return ResourceManager.GetString("ConsoleOutput_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Status: PASS.
        /// </summary>
        public static string ConsoleOutput_StatusPass {
            get {
                return ResourceManager.GetString("ConsoleOutput_StatusPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Status: FAIL.
        /// </summary>
        public static string ConsoleOutput_StatusFail {
            get {
                return ResourceManager.GetString("ConsoleOutput_StatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Errors ({0}):.
        /// </summary>
        public static string ConsoleOutput_Errors {
            get {
                return ResourceManager.GetString("ConsoleOutput_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Key: {0}.
        /// </summary>
        public static string ConsoleOutput_Key {
            get {
                return ResourceManager.GetString("ConsoleOutput_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         {0}: {1}.
        /// </summary>
        public static string ConsoleOutput_ValidatorType {
            get {
                return ResourceManager.GetString("ConsoleOutput_ValidatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         Current value: {0}.
        /// </summary>
        public static string ConsoleOutput_CurrentValue {
            get {
                return ResourceManager.GetString("ConsoleOutput_CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Validated {0} rule(s).
        /// </summary>
        public static string ConsoleOutput_ValidatedRules {
            get {
                return ResourceManager.GetString("ConsoleOutput_ValidatedRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed: Environment ID is required but was null or empty. Context: {0}. Please provide a valid environment ID to validate..
        /// </summary>
        public static string RuleEngine_ValidationFailed_EnvironmentIdRequired {
            get {
                return ResourceManager.GetString("RuleEngine_ValidationFailed_EnvironmentIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed: Environment '{0}' has an invalid or empty path. Context: {1}. Environment name: '{2}'. Please ensure the environment definition includes a valid 'path' property pointing to the app settings file..
        /// </summary>
        public static string RuleEngine_ValidationFailed_EnvironmentInvalidPath {
            get {
                return ResourceManager.GetString("RuleEngine_ValidationFailed_EnvironmentInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed: Required file not found. Environment ID: '{0}'. File path: '{1}'. Context: {2}. Error: {3}. Please ensure the configuration file and referenced app settings files exist and are accessible..
        /// </summary>
        public static string RuleEngine_ValidationFailed_FileNotFound {
            get {
                return ResourceManager.GetString("RuleEngine_ValidationFailed_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed: Configuration error detected. Environment ID: '{0}'. Context: {1}. Error: {2}. Please review the configuration file structure and fix any validation errors..
        /// </summary>
        public static string RuleEngine_ValidationFailed_ConfigurationError {
            get {
                return ResourceManager.GetString("RuleEngine_ValidationFailed_ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed: Validation error occurred. Environment ID: '{0}'. Context: {1}. Error: {2}. Please review the validation rules and fix any rule violations..
        /// </summary>
        public static string RuleEngine_ValidationFailed_ValidationError {
            get {
                return ResourceManager.GetString("RuleEngine_ValidationFailed_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed: Unexpected error occurred. Environment ID: '{0}'. Context: {1}. Exception type: {2}. Error: {3}. This is an unexpected error. Please check the logs for more details and contact support if the issue persists..
        /// </summary>
        public static string RuleEngine_ValidationFailed_UnexpectedError {
            get {
                return ResourceManager.GetString("RuleEngine_ValidationFailed_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed: Environment '{0}' not found in configuration.{1} Total environments in configuration: {2}. Available environment IDs: {3}. Please verify the environment ID is correct and matches one of the available environments in the configuration file..
        /// </summary>
        public static string RuleEngine_EnvironmentNotFound {
            get {
                return ResourceManager.GetString("RuleEngine_EnvironmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No environments found in configuration..
        /// </summary>
        public static string RuleEngine_NoEnvironmentsFound {
            get {
                return ResourceManager.GetString("RuleEngine_NoEnvironmentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed: Required file not found. Context: {0}. File path: '{1}'. Error: {2}. Please ensure the configuration file and referenced app settings files exist and are accessible..
        /// </summary>
        public static string RuleEngine_ValidationFailed_FileNotFound_AllEnvironments {
            get {
                return ResourceManager.GetString("RuleEngine_ValidationFailed_FileNotFound_AllEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed: Configuration error detected. Context: {0}. Error: {1}. Please review the configuration file structure and fix any validation errors..
        /// </summary>
        public static string RuleEngine_ValidationFailed_ConfigurationError_AllEnvironments {
            get {
                return ResourceManager.GetString("RuleEngine_ValidationFailed_ConfigurationError_AllEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error: Unsupported validator type '{0}'. Configuration key: '{1}'. Value: {2}. Error: {3}. Please use a supported validator type. Check the configuration for valid validator types..
        /// </summary>
        public static string ValidationMessageFormatter_UnsupportedValidator {
            get {
                return ResourceManager.GetString("ValidationMessageFormatter_UnsupportedValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error: Invalid validation argument. Configuration key: '{0}'. Validator type: '{1}'. Value: {2}. Error: {3}. Please check the validator configuration and ensure all required properties are provided..
        /// </summary>
        public static string ValidationMessageFormatter_InvalidArgument {
            get {
                return ResourceManager.GetString("ValidationMessageFormatter_InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error: Unexpected error occurred during validation. Configuration key: '{0}'. Validator type: '{1}'. Value: {2}. Exception type: {3}. Error: {4}. This is an unexpected error. Please check the logs for more details..
        /// </summary>
        public static string ValidationMessageFormatter_UnexpectedError {
            get {
                return ResourceManager.GetString("ValidationMessageFormatter_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment '{0}' {1}: {2}.
        /// </summary>
        public static string ValidationMessageFormatter_EnvironmentError {
            get {
                return ResourceManager.GetString("ValidationMessageFormatter_EnvironmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual value: {0}. Expected value: {1}..
        /// </summary>
        public static string ValidationMessageFormatter_ValueComparison {
            get {
                return ResourceManager.GetString("ValidationMessageFormatter_ValueComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found for environment '{0}': {1}.
        /// </summary>
        public static string ValidationMessageFormatter_FileNotFound {
            get {
                return ResourceManager.GetString("ValidationMessageFormatter_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error for environment '{0}': {1}.
        /// </summary>
        public static string ValidationMessageFormatter_ConfigurationError {
            get {
                return ResourceManager.GetString("ValidationMessageFormatter_ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load or validate environment '{0}': {1}.
        /// </summary>
        public static string ValidationMessageFormatter_FailedToLoadEnvironment {
            get {
                return ResourceManager.GetString("ValidationMessageFormatter_FailedToLoadEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment ID: '{0}'. .
        /// </summary>
        public static string ValidationMessageFormatter_Context_EnvironmentId {
            get {
                return ResourceManager.GetString("ValidationMessageFormatter_Context_EnvironmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context: {0}. .
        /// </summary>
        public static string ValidationMessageFormatter_Context_ContextDesc {
            get {
                return ResourceManager.GetString("ValidationMessageFormatter_Context_ContextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: JSON content is required but was null or empty. Please provide valid JSON content to validate against the schema..
        /// </summary>
        public static string JsonSchemaValidator_JsonContentRequired {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_JsonContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Schema content is required but was null or empty. Please provide valid JSON schema content to validate against..
        /// </summary>
        public static string JsonSchemaValidator_SchemaContentRequired {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_SchemaContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Schema file path is required but was null or empty. Please provide a valid path to the JSON schema file..
        /// </summary>
        public static string JsonSchemaValidator_SchemaFilePathRequired {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_SchemaFilePathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Invalid JSON format detected{0}. JSON parsing error: {1}. Please verify the JSON syntax is valid (check for missing commas, brackets, quotes, etc.) and try again..
        /// </summary>
        public static string JsonSchemaValidator_InvalidJsonFormat {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_InvalidJsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Unexpected error occurred during schema parsing. Exception type: {0}. Error: {1}. This is an unexpected error. Please check the logs for more details..
        /// </summary>
        public static string JsonSchemaValidator_UnexpectedErrorSchemaParsing {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_UnexpectedErrorSchemaParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Schema file not found. Schema path: '{0}' (resolved to: '{1}'). Please ensure the schema file exists and the path is correct. Check for typos, verify the file location, and ensure you have read permissions..
        /// </summary>
        public static string JsonSchemaValidator_SchemaFileNotFound {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_SchemaFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Schema file not found. Schema path: '{0}' (resolved to: '{1}'). Error: {2}. Please ensure the schema file exists and the path is correct..
        /// </summary>
        public static string JsonSchemaValidator_SchemaFileNotFound_WithError {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_SchemaFileNotFound_WithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: I/O error occurred while reading the schema file. Schema path: '{0}' (resolved to: '{1}'). Error: {2}. Possible causes: file is locked by another process, disk is full, network path is unavailable, or insufficient permissions. Please check file access permissions and ensure the file is not in use by another application..
        /// </summary>
        public static string JsonSchemaValidator_IOError {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_IOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Access denied reading schema file. Schema path: '{0}' (resolved to: '{1}'). Error: {2}. The current user does not have read permissions for this file. Please check file permissions and ensure the file is readable by the current user or process..
        /// </summary>
        public static string JsonSchemaValidator_AccessDenied {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Unexpected error occurred while reading schema file. Schema path: '{0}' (resolved to: '{1}'). Exception type: {2}. Error: {3}. This is an unexpected error. Please check the logs for more details..
        /// </summary>
        public static string JsonSchemaValidator_UnexpectedErrorReadingFile {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_UnexpectedErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Unexpected error occurred during schema validation. Exception type: {0}. Error: {1}. This is an unexpected error. Please check the logs for more details..
        /// </summary>
        public static string JsonSchemaValidator_UnexpectedErrorValidation {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_UnexpectedErrorValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Missing required property at JSON path '{0}'. Property path: '{1}'. Error kind: {2}. Missing properties: {3}. Please add the required property to the JSON document..
        /// </summary>
        public static string JsonSchemaValidator_MissingRequiredProperty {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_MissingRequiredProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Missing required property at JSON path '{0}'. Property path: '{1}'. Error kind: {2}. Please add the required property to the JSON document..
        /// </summary>
        public static string JsonSchemaValidator_MissingRequiredProperty_NoProperties {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_MissingRequiredProperty_NoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Invalid type at JSON path '{0}'. Property path: '{1}'. Expected type: {2}. Actual type: {3}. Please ensure the value matches the expected type specified in the schema..
        /// </summary>
        public static string JsonSchemaValidator_InvalidType {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Invalid type at JSON path '{0}'. Property path: '{1}'. Expected type: {2}. Please ensure the value matches the expected type specified in the schema..
        /// </summary>
        public static string JsonSchemaValidator_InvalidType_NoActualType {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_InvalidType_NoActualType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema validation failed: Validation error at JSON path '{0}'. Property path: '{1}'. Error kind: {2}. Error details: {3}. Please review the schema requirements and fix the JSON document accordingly..
        /// </summary>
        public static string JsonSchemaValidator_ValidationError {
            get {
                return ResourceManager.GetString("JsonSchemaValidator_ValidationError", resourceCulture);
            }
        }
    }
}

